```{r t24a}
jjj <- 24
source('topic_summary_data.R')
opts_knit$set(eval.after = "fig.cap")
```

```{r t24b, fig.cap=the_categories$subject[jjj], fig.height= 5.2}
source('topic_summary_overall_graph.R')
```

```{r t24c, fig.cap=paste(the_categories$subject[jjj], "Articles in Each Journal")}
cat("<br>")
source('topic_summary_facet_graph.R')
```

```{r t24d}
cat("<br>")
source('topic_summary_char_art.R')
temp_dt
```

```{r t24e}
cat("<br>")
source('topic_summary_high_cites.R')
if(is_high_cites == 1)
	{cat("<br>")}
if(is_high_cites == 1)
	{high_table}
if(is_high_cites == 1)
	{cat("<br>")}
cat("\n
	**Comments**
	\n")
```

```{r olp-notes}
# 
# Note I had to change the scales here, especially because of the Aristotelian Society.
# 
# Compare max values for different journals.
# 
# Note that there are 30 highly cited articles. Bernard Williams, Frank Jackson, Stephen Yablo, Philippa Foot. Kind of good writers. (Though also Wittgenstein, so shrug emoji.)
# 
# Binary sort
# 
# Not actually a subject, more a style. Look at the keywords. Maybe do the keyword graphs. And maybe even facet the graph for surely, certainly, perhaps, quite.
# 
# It is driven a lot by Aristotelian Society. But stays at 10% of PR for years (maybe Malcolm's influence). Never really catches on a J Phil, and especially at BJPS. Going up and up at PPR and Ethics.
# 
# Advice to young players: stop word out a bunch of these words.
```